FROM --platform=linux/amd64 node:18

ENV DATABASE_URL="DATABASE_URL"
ENV JWT_SECRET="JWT_SECRET"
ENV STATUS_SERVICE_URL="STATUS_SERVICE_URL"
ENV ORDER_SERVICE_URL="ORDER_SERVICE_URL"
ENV MERCADO_PAGO_GENERATE_PAYMENT="MERCADO_PAGO_GENERATE_PAYMENT"
ENV MERCADO_PAGO_WEBHOOK_URL="MERCADO_PAGO_WEBHOOK_URL"
ENV MERCADO_PAGO_API_HOST="MERCADO_PAGO_API_HOST"
ENV MERCADO_PAGO_BEARER_TOKEN="MERCADO_PAGO_BEARER_TOKEN"
ENV MERCADO_PAGO_USER_ID="MERCADO_PAGO_USER_ID"
ENV MERCADO_PAGO_EXTERNAL_POS_ID="MERCADO_PAGO_EXTERNAL_POS_ID"

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

RUN yarn prisma generate

EXPOSE 3005

CMD yarn prisma migrate dev && yarn dev