@host = http://localhost:3005
@service-prefix = payment-service
# @host = http://localhost:31100


# @name update-payment
PUT {{host}}/payment-service/70500c1c-35f8-4620-ba53-fbbfc6e82acb/paid


### 

# @name webhook
POST {{host}}/{{service-prefix}}/mercado-pago/webhook
content-type: application/json

{
  "resource": "https://api.mercadolibre.com/merchant_orders/18851567123",
  "topic": "merchant_order"
}

